// FreshwaterFishData.js
const freshwaterFishSpecies = [
  {
    name: 'Neon Tetra',
    description: 'Neon Tetras are among the most popular tetras due to their striking iridescent blue and red colors.',
    temperament: 'Peaceful',
    maxGrowthSize: 'Around 1.5 inches (4 cm)',
    img: 'https://as1.ftcdn.net/v2/jpg/04/88/85/40/1000_F_488854015_30rnKc7hKZQpclCkm0rqAH5Fo2MYSADa.jpg',
    size: 'Small',
    species: 'Paracheirodon innesi',
    family: 'Characidae',
  },
  {
    name: 'Cardinal Tetra',
    description: 'Cardinal Tetras are known for their vibrant red and blue colors, similar to Neon Tetras.',
    temperament: 'Peaceful',
    maxGrowthSize: 'Around 1.5 inches (4 cm)',
    img: 'https://example.com/cardinal-tetra-image.jpg',
    size: 'Small',
    species: 'Paracheirodon axelrodi',
    family: 'Characidae',
  },
  {
    name: 'Ember Tetra',
    description: 'Ember Tetras have a beautiful fiery orange coloration that adds warmth to any aquarium.',
    temperament: 'Peaceful',
    maxGrowthSize: 'Around 1 inch (2.5 cm)',
    img: 'https://example.com/ember-tetra-image.jpg',
    size: 'Small',
    species: 'Hyphessobrycon amandae',
    family: 'Characidae',
  },
  {
    name: 'Black Neon Tetra',
    description: 'Black Neon Tetras feature a combination of black and silver colors, creating a striking appearance.',
    temperament: 'Peaceful',
    maxGrowthSize: 'Around 1.5 inches (4 cm)',
    img: 'https://example.com/black-neon-tetra-image.jpg',
    size: 'Small',
    species: 'Hyphessobrycon herbertaxelrodi',
    family: 'Characidae',
  },
  {
    name: 'Vampire Tetra',
    description: 'Vampire Tetras are known for their sharp teeth and predatory behavior, requiring a larger tank.',
    temperament: 'Aggressive',
    maxGrowthSize: 'Around 14 inches (35 cm)',
    img: 'https://example.com/vampire-tetra-image.jpg',
    size: 'Large',
    species: 'Hydrolycus scomberoides',
    family: 'Cynodontidae',
  },
  {
    name: 'Congo Tetra',
    description: 'Congo Tetras are large, peaceful tetras known for their distinctive coloration and fin extensions.',
    temperament: 'Peaceful',
    maxGrowthSize: 'Around 3 inches (8 cm)',
    img: 'https://example.com/congo-tetra-image.jpg',
    size: 'Medium',
    species: 'Phenacogrammus interruptus',
    family: 'Alestidae',
  },
  {
    name: 'Bleeding Heart Tetra',
    description: 'Bleeding Heart Tetras are named for the heart-shaped red marking on their silver bodies.',
    temperament: 'Peaceful',
    maxGrowthSize: 'Around 2.5 inches (6 cm)',
    img: 'https://example.com/bleeding-heart-tetra-image.jpg',
    size: 'Small',
    species: 'Hyphessobrycon erythrostigma',
    family: 'Characidae',
  },
  {
    name: 'Black Skirt Tetra',
    description: 'Black Skirt Tetras are known for their distinctive black markings on their fins and bodies.',
    temperament: 'Semi-Aggressive',
    maxGrowthSize: 'Around 2 inches (5 cm)',
    img: 'https://example.com/black-skirt-tetra-image.jpg',
    size: 'Small',
    species: 'Gymnocorymbus ternetzi',
    family: 'Characidae',
  },
  {
    name: 'Serpae Tetra',
    description: 'Serpae Tetras are known for their vibrant red coloration and schooling behavior.',
    temperament: 'Semi-Aggressive',
    maxGrowthSize: 'Around 1.5 inches (4 cm)',
    img: 'https://example.com/serpae-tetra-image.jpg',
    size: 'Small',
    species: 'Hyphessobrycon eques',
    family: 'Characidae',
  },
  {
    name: 'Green Neon Tetra',
    description: 'Green Neon Tetras have a bright green stripe along their bodies, adding a unique touch to aquariums.',
    temperament: 'Peaceful',
    maxGrowthSize: 'Around 1.5 inches (4 cm)',
    img: 'https://example.com/green-neon-tetra-image.jpg',
    size: 'Small',
    species: 'Paracheirodon simulans',
    family: 'Characidae',
  },
  {
    name: 'Bloodfin Tetra',
    description: 'Bloodfin Tetras are known for their distinctive red fins, adding a splash of color to aquariums.',
    temperament: 'Peaceful',
    maxGrowthSize: 'Around 2 inches (5 cm)',
    img: 'https://example.com/bloodfin-tetra-image.jpg',
    size: 'Small',
    species: 'Aphyocharax anisitsi',
    family: 'Characidae',
  },
  {
    name: 'Rummynose Tetra',
    description: 'Rummynose Tetras have a distinct red nose, adding a playful and vibrant element to aquariums.',
    temperament: 'Peaceful',
    maxGrowthSize: 'Around 2 inches (5 cm)',
    img: 'https://example.com/rummynose-tetra-image.jpg',
    size: 'Small',
    species: 'Hemigrammus rhodostomus',
    family: 'Characidae',
  },
  {
    name: 'Emperor Tetra',
    description: 'Emperor Tetras are known for their striking blue and black coloration, adding elegance to aquariums.',
    temperament: 'Peaceful',
    maxGrowthSize: 'Around 2 inches (5 cm)',
    img: 'https://example.com/emperor-tetra-image.jpg',
    size: 'Small',
    species: 'Nematobrycon palmeri',
    family: 'Characidae',
  },
  {
    name: 'Von Rio Tetra',
    description: 'Von Rio Tetras are colorful and active, creating a vibrant and lively aquarium environment.',
    temperament: 'Peaceful',
    maxGrowthSize: 'Around 1.5 inches (4 cm)',
    img: 'https://example.com/von-rio-tetra-image.jpg',
    size: 'Small',
    species:"Hyphessobrycon flammeus",
    family: "Characidae"
  },
  {
    name: 'Guppy',
    description: 'Guppies are known for their vibrant colors and live-bearing reproduction.',
    temperament: 'Peaceful',
    maxGrowthSize: 'Around 2 inches (5 cm)',
    species: 'Poecilia reticulata',
  },
  {
    name: 'Platy',
    description: 'Platies are colorful and easy to care for livebearers, making them great for community aquariums.',
    temperament: 'Peaceful',
    maxGrowthSize: 'Around 2.5 inches (6 cm)',
    species: 'Xiphophorus maculatus',
  },
  {
    name: 'Corydoras Catfish',
    description: 'Corydoras Catfish are bottom-dwelling fish that help keep the tank clean from uneaten food. While sometimes we see them pick at feces but it is good advice take that as a sign to feed them a bit more',
    temperament: 'Peaceful',
    maxGrowthSize: 'Around 2.5 inches (6 cm)',
    species: 'Corydoras',
  },

    // cat by fish species with descriptions, temperament, and max growth size here
];
  
  export default freshwaterFishSpecies;
  